version: '3.8'

services:
  course-scheduling-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: im-course-scheduling
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - .env
    volumes:
      - courses_data:/app/courses_data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "const http = require('http'); http.get('http://localhost:3000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1); }).on('error', () => { process.exit(1); });"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - course-scheduling-network

volumes:
  courses_data:
    driver: local

networks:
  course-scheduling-network:
    driver: bridge
